#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 10 18:53:08 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1p1.zip
