Welcome Message:false
Zoom Level:2
Old North:false
Color Picker Mode:0
Hide Minimap:false
Update Notifier:true
Display Biome:false
Display Coordinates:1
Map Corner:0
Map Size:1
Square Map:false
Rotation:false
Waypoint Beacons:false
Waypoint Signs:true
Enable Cave Mode:true
Move Map Below Status Effect Icons:true
Move Scoreboard Below Map:true
Dynamic Lighting:true
Height Map:true
Slope Map:true
Water Transparency:true
Block Transparency:true
Biomes:true
Biome Overlay:0
Chunk Grid:false
Slime Chunks:false
World Border:true
Filtering:false
Teleport Command:tp %p %x %y %z
Waypoint Sort By:1
Waypoint Max Distance:1000
Waypoint Sign Scale:1.0
Deathpoints:1
Waypoint Distance Unit Conversion:1
Show In-game Waypoint Names:2
Show In-game Waypoint Distances:2
Zoom Key:key.keyboard.z
Fullscreen Key:key.keyboard.unknown
Menu Key:key.keyboard.m
Waypoint Menu Key:key.keyboard.u
Waypoint Key:key.keyboard.n
Mob Key:key.keyboard.unknown
In-game Waypoint Key:key.keyboard.unknown
Toggle Minimap Key:key.keyboard.h
Radar Mode:2
Show Radar:true
Show Hostiles:true
Show Neutrals:false
Show Players:true
Filter Mob Icons:true
Outline Mob Icons:true
Show Player Helmets:true
Show Mob Helmets:true
Show Player Names:false
Show Mob Names:false
Font Scale:1.0
Show Facing:true
Radar CPU Rendering:false
Show Full Entity Names:false
Show Entity Elevation:true
Hide Sneaking Players:true
Hide Invisible Entities:true
Hidden Mobs:minecraft:,
Worldmap Zoom:1.5878984
Worldmap Minimum Zoom:0.5
Worldmap Maximum Zoom:16.0
Worldmap Cache Size:500
Show Worldmap Coordinates:true
Show Worldmap Waypoints:true
Show Worldmap Waypoint Names:true
Show Worldmap Distant Waypoints:true
